spring:
  application:
    name: amigoscode-rsu-api
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: richard
    password: "#FuckYourMum2020"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet